INSERT INTO jakartaee_get_started.dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Afghanistan', 'AF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Albania', 'AL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Algeria', 'DZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'American Samoa', 'AS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Andorra', 'AD');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Angola', 'AO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Anguilla', 'AI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Antarctica', 'AQ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Antigua and Barbuda', 'AG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Argentina', 'AR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Armenia', 'AM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Aruba', 'AW');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Australia', 'AU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Austria', 'AT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Azerbaijan', 'AZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bahamas', 'BS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bahrain', 'BH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bangladesh', 'BD');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Barbados', 'BB');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Belarus', 'BY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Belgium', 'BE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Belize', 'BZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Benin', 'BJ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bermuda', 'BM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bhutan', 'BT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bosnia and Herzegovina', 'BA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Botswana', 'BW');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bouvet Island', 'BV');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Brazil', 'BR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'British Indian Ocean Territory', 'IO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Brunei Darussalam', 'BN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Bulgaria', 'BG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Burkina Faso', 'BF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Burundi', 'BI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cambodia', 'KH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cameroon', 'CM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Canada', 'CA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cape Verde', 'CV');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cayman Islands', 'KY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Central African Republic', 'CF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Chad', 'TD');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Chile', 'CL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'China', 'CN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Christmas Island', 'CX');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cocos (Keeling) Islands', 'CC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Colombia', 'CO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Comoros', 'KM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Congo', 'CG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cook Islands', 'CK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Costa Rica', 'CR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Croatia', 'HR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cuba', 'CU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Cyprus', 'CY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Czech Republic', 'CZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Denmark', 'DK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Djibouti', 'DJ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Dominica', 'DM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Dominican Republic', 'DO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Ecuador', 'EC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Egypt', 'EG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'El Salvador', 'SV');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Equatorial Guinea', 'GQ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Eritrea', 'ER');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Estonia', 'EE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Ethiopia', 'ET');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Falkland Islands (Malvinas)' ,'FK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Faroe Islands', 'FO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Fiji', 'FJ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Finland', 'FI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'France', 'FR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'French Guiana', 'GF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'French Polynesia', 'PF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'French Southern Territories', 'TF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Gabon', 'GA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Gambia', 'GM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Georgia', 'GE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Germany', 'DE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Ghana', 'GH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Gibraltar', 'GI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Greece', 'GR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Greenland', 'GL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Grenada', 'GD');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Guadeloupe', 'GP');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Guam', 'GU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Guatemala', 'GT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Guernsey', 'GG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Guinea', 'GN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Guinea-Bissau', 'GW');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Guyana', 'GY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Haiti', 'HT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Heard Island and McDonald Islands', 'HM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Holy See (Vatican City State)' ,'VA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Honduras', 'HN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Hong Kong', 'HK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Hungary', 'HU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Iceland', 'IS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'India', 'IN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Indonesia', 'ID');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Iraq', 'IQ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Ireland', 'IE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Isle of Man', 'IM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Israel', 'IL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Italy', 'IT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Jamaica', 'JM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Japan', 'JP');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Jersey', 'JE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Jordan', 'JO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Kazakhstan', 'KZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Kenya', 'KE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Kiribati', 'KI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Kuwait', 'KW');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Kyrgyzstan', 'KG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Lao Peoples Democratic Republic', 'LA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Latvia', 'LV');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Lebanon', 'LB');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Lesotho', 'LS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Liberia', 'LR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Libya', 'LY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Liechtenstein', 'LI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Lithuania', 'LT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Luxembourg', 'LU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Macao', 'MO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Madagascar', 'MG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Malawi', 'MW');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Malaysia', 'MY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Maldives', 'MV');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Mali', 'ML');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Malta', 'MT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Marshall Islands', 'MH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Martinique', 'MQ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Mauritania', 'MR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Mauritius', 'MU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Mayotte', 'YT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Mexico', 'MX');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Monaco', 'MC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Mongolia', 'MN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Montenegro', 'ME');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Montserrat', 'MS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Morocco', 'MA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Mozambique', 'MZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Myanmar', 'MM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Namibia', 'NA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Nauru', 'NR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Nepal', 'NP');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Netherlands', 'NL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'New Caledonia', 'NC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'New Zealand', 'NZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Nicaragua', 'NI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Niger', 'NE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Nigeria', 'NG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Niue', 'NU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Norfolk Island', 'NF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Northern Mariana Islands', 'MP');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Norway', 'NO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Oman', 'OM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Pakistan', 'PK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Palau', 'PW');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Panama', 'PA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Papua New Guinea', 'PG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Paraguay', 'PY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Peru', 'PE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Philippines', 'PH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Pitcairn', 'PN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Poland', 'PL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Portugal', 'PT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Puerto Rico', 'PR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Qatar', 'QA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Romania', 'RO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Russian Federation', 'RU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Rwanda', 'RW');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Saint Kitts and Nevis', 'KN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Saint Lucia', 'LC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Saint Martin (French part)' ,'MF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Saint Pierre and Miquelon', 'PM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Saint Vincent and the Grenadines', 'VC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Samoa', 'WS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'San Marino', 'SM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Sao Tome and Principe', 'ST');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Saudi Arabia', 'SA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Senegal', 'SN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Serbia', 'RS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Seychelles', 'SC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Sierra Leone', 'SL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Singapore', 'SG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Sint Maarten (Dutch part)' ,'SX');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Slovakia', 'SK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Slovenia', 'SI');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Solomon Islands', 'SB');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Somalia', 'SO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'South Africa', 'ZA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'South Sudan', 'SS');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Spain', 'ES');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Sri Lanka', 'LK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Sudan', 'SD');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Suriname', 'SR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Svalbard and Jan Mayen', 'SJ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Swaziland', 'SZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Sweden', 'SE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Switzerland', 'CH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Syrian Arab Republic', 'SY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Tajikistan', 'TJ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Thailand', 'TH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Timor-Leste', 'TL');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Togo', 'TG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Tokelau', 'TK');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Tonga', 'TO');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Trinidad and Tobago', 'TT');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Tunisia', 'TN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Turkey', 'TR');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Turkmenistan', 'TM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Turks and Caicos Islands', 'TC');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Tuvalu', 'TV');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Uganda', 'UG');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Ukraine', 'UA');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'United Arab Emirates', 'AE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'United Kingdom', 'GB');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'United States', 'US');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'United States Minor Outlying Islands', 'UM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Uruguay', 'UY');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Uzbekistan', 'UZ');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Vanuatu', 'VU');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Viet Nam', 'VN');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Wallis and Futuna', 'WF');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Western Sahara', 'EH');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Yemen', 'YE');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Zambia', 'ZM');
INSERT INTO dev_schema.pais (id, name, iso) VALUES (nextval('dev_schema.pais_id_seq'),'Zimbabwe', 'ZW');